from arcade import Window
from arcade.application import View
from arcade.types import RGBA255
from collections.abc import Callable

__all__ = ['get_display_size', 'get_window', 'set_window', 'close_window', 'run', 'exit', 'start_render', 'finish_render', 'set_background_color', 'schedule', 'unschedule', 'schedule_once']

def get_display_size(screen_id: int = 0) -> tuple[int, int]: ...
def get_window() -> Window: ...
def set_window(window: Window | None) -> None: ...
def close_window() -> None: ...
def run(view: View | None = None) -> None: ...
def exit() -> None: ...
def start_render(pixelated: bool = False, blend: bool = True) -> None: ...
def finish_render() -> None: ...
def set_background_color(color: RGBA255) -> None: ...
def schedule(function_pointer: Callable, interval: float): ...
def unschedule(function_pointer: Callable): ...
def schedule_once(function_pointer: Callable, delay: float): ...
